<?php
/**
 * Git Auto-Deploy Installer
 * Заливай на хостинг, открывай в браузере и следуй шагам
 */

session_start();

// Сброс только по явному запросу
if (isset($_GET['reset'])) {
    $_SESSION = [];
}

// Первый заход — инициализируем шаг
if (!isset($_SESSION['step'])) {
    $_SESSION['step'] = 1;
}

define('INSTALLER_VERSION', '1.0');
define('CONFIG_FILE', __DIR__ . '/.deploy_config.php');
define('DEPLOY_FILE', __DIR__ . '/deploy.php');
define('LOG_FILE', __DIR__ . '/deploy.log');

// --- Helpers ---

function shell($cmd) {
    return shell_exec($cmd . ' 2>&1');
}

function ok($msg) {
    return ['status' => 'ok', 'msg' => $msg];
}

function err($msg) {
    return ['status' => 'error', 'msg' => $msg];
}

function warn($msg) {
    return ['status' => 'warn', 'msg' => $msg];
}

function current_step() {
    return $_SESSION['step'] ?? 1;
}

function set_step($n) {
    $_SESSION['step'] = $n;
}

// --- Диагностика окружения ---

function check_env() {
    $results = [];

    // Путь и пользователь
    $results['dir']  = ok(__DIR__);
    $results['user'] = ok(trim(shell('whoami')));

    // shell_exec
    $test = shell('echo ok');
    $results['shell_exec'] = trim($test) === 'ok'
        ? ok('Доступен')
        : err('Заблокирован — деплой невозможен');

    // git
    $git = shell('git --version');
    $results['git'] = str_contains($git, 'git version')
        ? ok(trim($git))
        : err('Git не найден');

    // Права на запись
    $results['writable'] = is_writable(__DIR__)
        ? ok('Папка доступна для записи')
        : err('Нет прав на запись в папку');

    return $results;
}

// --- Проверка репозитория ---

function check_repo($dir, $branch) {
    $results = [];

    // Существует ли папка
    if (!is_dir($dir)) {
        $results['dir'] = err("Папка не существует: {$dir}");
        return $results;
    }
    $results['dir'] = ok("Папка существует");

    // Есть ли .git
    $status = shell("cd " . escapeshellarg($dir) . " && git status");
    if (str_contains($status, 'not a git repository')) {
        $results['git_repo'] = err('Репозиторий не инициализирован — нужен git clone/init');
        return $results;
    }
    $results['git_repo'] = ok('Git репозиторий найден');

    // Текущая ветка
    $current_branch = trim(shell("cd " . escapeshellarg($dir) . " && git branch --show-current"));
    if ($current_branch !== $branch) {
        $results['branch'] = warn("Текущая ветка: '{$current_branch}', ожидается: '{$branch}'");
    } else {
        $results['branch'] = ok("Ветка: {$branch}");
    }

    // Remote
    $remote = trim(shell("cd " . escapeshellarg($dir) . " && git remote get-url origin"));
    if (empty($remote)) {
        $results['remote'] = err('Remote origin не настроен');
    } else {
        $results['remote'] = ok("Remote: {$remote}");
    }

    // Тест git fetch
    $fetch = shell("cd " . escapeshellarg($dir) . " && git fetch origin");
    if (str_contains($fetch, 'Permission denied') || str_contains($fetch, 'fatal')) {
        $results['fetch'] = err("Ошибка fetch: {$fetch}");
    } else {
        $results['fetch'] = ok('git fetch origin — успешно');
    }

    return $results;
}

// --- Инициализация репо ---

function init_repo($dir, $repo_url, $branch) {
    $log = [];

    // git init
    $out = shell("cd " . escapeshellarg($dir) . " && git init");
    $log[] = ['cmd' => 'git init', 'out' => $out];

    // remote add
    $out = shell("cd " . escapeshellarg($dir) . " && git remote add origin " . escapeshellarg($repo_url));
    $log[] = ['cmd' => 'git remote add origin', 'out' => $out];

    // fetch
    $out = shell("cd " . escapeshellarg($dir) . " && git fetch origin");
    $log[] = ['cmd' => 'git fetch origin', 'out' => $out];

    // checkout branch
    $out = shell("cd " . escapeshellarg($dir) . " && git checkout -b {$branch} origin/{$branch}");
    if (str_contains($out, 'already exists')) {
        $out = shell("cd " . escapeshellarg($dir) . " && git checkout {$branch}");
    }
    $log[] = ['cmd' => "git checkout {$branch}", 'out' => $out];

    // reset hard
    $out = shell("cd " . escapeshellarg($dir) . " && git reset --hard origin/{$branch}");
    $log[] = ['cmd' => "git reset --hard origin/{$branch}", 'out' => $out];

    return $log;
}

// --- Генерация deploy.php ---

function generate_deploy($dir, $branch, $secret) {
    return <<<PHP
<?php
/**
 * Auto-Deploy Webhook
 * Generated by Git Installer v1.0
 */

define('SECRET',      '{$secret}');
define('PROJECT_DIR', '{$dir}');
define('LOG_FILE',    __DIR__ . '/deploy.log');
define('BRANCH',      '{$branch}');

\$payload   = file_get_contents('php://input');
\$signature = \$_SERVER['HTTP_X_HUB_SIGNATURE_256'] ?? '';
\$expected  = 'sha256=' . hash_hmac('sha256', \$payload, SECRET);

log_msg('Webhook получен');

if (!\$signature || !hash_equals(\$expected, \$signature)) {
    http_response_code(403);
    log_msg('ОШИБКА: неверная подпись');
    die('Forbidden');
}

\$data = json_decode(\$payload, true);
\$ref  = \$data['ref'] ?? '';

if (\$ref !== 'refs/heads/' . BRANCH) {
    log_msg("Пропуск: ветка {\$ref}");
    die('Not target branch');
}

log_msg('=== Деплой начат ===');

\$commands = [
    'git fetch origin',
    'git reset --hard origin/' . BRANCH,
];

foreach (\$commands as \$cmd) {
    \$out = shell_exec('cd ' . escapeshellarg(PROJECT_DIR) . " && {\$cmd} 2>&1");
    log_msg("[{\$cmd}]\\n" . trim(\$out));
}

log_msg('=== Готово ===');
http_response_code(200);
echo 'OK';

function log_msg(\$msg) {
    file_put_contents(LOG_FILE, date('Y-m-d H:i:s') . ' ' . \$msg . PHP_EOL, FILE_APPEND);
}
PHP;
}

// --- Обработка POST ---

$action  = $_POST['action'] ?? '';
$message = null;
$data    = [];

if ($action === 'next_step') {
    set_step(current_step() + 1);
}

if ($action === 'check_env') {
    $data = check_env();
    if ($data['shell_exec']['status'] === 'ok' && $data['git']['status'] === 'ok') {
        set_step(2);
    }
}

if ($action === 'check_repo') {
    $dir    = trim($_POST['project_dir'] ?? __DIR__);
    $branch = trim($_POST['branch'] ?? 'main');
    $repo   = trim($_POST['repo_url'] ?? '');

    $_SESSION['project_dir'] = $dir;
    $_SESSION['branch']      = $branch;
    $_SESSION['repo_url']    = $repo;

    $data = check_repo($dir, $branch);

    $all_ok = !empty($data) && array_reduce($data, fn($carry, $item) => $carry && $item['status'] !== 'error', true);
    if ($all_ok) {
        set_step(3);
    }
}

if ($action === 'init_repo') {
    $dir    = $_SESSION['project_dir'] ?? __DIR__;
    $branch = $_SESSION['branch'] ?? 'main';
    $repo   = $_SESSION['repo_url'] ?? '';

    $data = init_repo($dir, $repo, $branch);
    // После инициализации проверяем снова
    $check = check_repo($dir, $branch);
    $all_ok = !empty($check) && array_reduce($check, fn($carry, $item) => $carry && $item['status'] !== 'error', true);
    if ($all_ok) {
        set_step(3);
    }
}

if ($action === 'generate_deploy') {
    $dir    = $_SESSION['project_dir'] ?? __DIR__;
    $branch = $_SESSION['branch'] ?? 'main';
    $secret = trim($_POST['secret'] ?? '');

    if (empty($secret)) {
        $secret = bin2hex(random_bytes(16));
    }

    $_SESSION['secret'] = $secret;

    $deploy_code = generate_deploy($dir, $branch, $secret);
    file_put_contents(DEPLOY_FILE, $deploy_code);

    $webhook_url = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI']) . '/deploy.php';
    $_SESSION['webhook_url'] = $webhook_url;

    set_step(4);
}

if ($action === 'test_deploy') {
    $dir    = $_SESSION['project_dir'] ?? __DIR__;
    $branch = $_SESSION['branch'] ?? 'main';

    $out1 = shell("cd " . escapeshellarg($dir) . " && git fetch origin");
    $out2 = shell("cd " . escapeshellarg($dir) . " && git reset --hard origin/{$branch}");

    file_put_contents(LOG_FILE, date('Y-m-d H:i:s') . " [ТЕСТ] fetch: {$out1}\n", FILE_APPEND);
    file_put_contents(LOG_FILE, date('Y-m-d H:i:s') . " [ТЕСТ] reset: {$out2}\n", FILE_APPEND);

    $data = ['fetch' => $out1, 'reset' => $out2];
    set_step(5);
}

$step = current_step();

// --- HTML ---
?>
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Git Deploy Installer</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&family=Unbounded:wght@400;700&display=swap');

  :root {
    --bg: #0a0a0f;
    --surface: #111118;
    --border: #1e1e2e;
    --accent: #00ff88;
    --accent2: #7c3aed;
    --warn: #f59e0b;
    --err: #ef4444;
    --text: #e2e8f0;
    --muted: #64748b;
    --mono: 'JetBrains Mono', monospace;
    --head: 'Unbounded', sans-serif;
  }

  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    background: var(--bg);
    color: var(--text);
    font-family: var(--mono);
    font-size: 14px;
    min-height: 100vh;
    padding: 40px 20px;
  }

  .wrap {
    max-width: 760px;
    margin: 0 auto;
  }

  header {
    margin-bottom: 48px;
    border-left: 3px solid var(--accent);
    padding-left: 20px;
  }

  header h1 {
    font-family: var(--head);
    font-size: 22px;
    color: var(--accent);
    letter-spacing: -0.5px;
    margin-bottom: 6px;
  }

  header p {
    color: var(--muted);
    font-size: 12px;
  }

  /* Steps nav */
  .steps {
    display: flex;
    gap: 0;
    margin-bottom: 40px;
    border: 1px solid var(--border);
    border-radius: 8px;
    overflow: hidden;
  }

  .step-item {
    flex: 1;
    padding: 12px 8px;
    text-align: center;
    font-size: 11px;
    color: var(--muted);
    border-right: 1px solid var(--border);
    background: var(--surface);
    transition: all 0.2s;
  }

  .step-item:last-child { border-right: none; }

  .step-item.active {
    background: rgba(0,255,136,0.08);
    color: var(--accent);
    border-bottom: 2px solid var(--accent);
  }

  .step-item.done {
    color: var(--accent);
    opacity: 0.5;
  }

  .step-num {
    display: block;
    font-family: var(--head);
    font-size: 16px;
    margin-bottom: 3px;
  }

  /* Card */
  .card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 32px;
    margin-bottom: 20px;
  }

  .card h2 {
    font-family: var(--head);
    font-size: 16px;
    margin-bottom: 20px;
    color: var(--text);
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .card h2 .num {
    background: var(--accent);
    color: #000;
    width: 26px;
    height: 26px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    flex-shrink: 0;
  }

  /* Form */
  label {
    display: block;
    color: var(--muted);
    font-size: 11px;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  input[type=text] {
    width: 100%;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 10px 14px;
    color: var(--text);
    font-family: var(--mono);
    font-size: 13px;
    margin-bottom: 16px;
    outline: none;
    transition: border-color 0.2s;
  }

  input[type=text]:focus {
    border-color: var(--accent);
  }

  /* Button */
  .btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    background: var(--accent);
    color: #000;
    border: none;
    border-radius: 6px;
    padding: 10px 20px;
    font-family: var(--mono);
    font-size: 13px;
    font-weight: 700;
    cursor: pointer;
    transition: opacity 0.2s;
  }

  .btn:hover { opacity: 0.85; }

  .btn-ghost {
    background: transparent;
    color: var(--accent);
    border: 1px solid var(--accent);
  }

  /* Check results */
  .checks { margin: 20px 0; }

  .check-row {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    padding: 10px 0;
    border-bottom: 1px solid var(--border);
    font-size: 13px;
  }

  .check-row:last-child { border-bottom: none; }

  .check-key {
    color: var(--muted);
    min-width: 120px;
    font-size: 11px;
    padding-top: 2px;
    text-transform: uppercase;
  }

  .check-val { flex: 1; word-break: break-all; }

  .badge {
    padding: 2px 8px;
    border-radius: 4px;
    font-size: 10px;
    font-weight: 700;
    flex-shrink: 0;
  }

  .badge-ok   { background: rgba(0,255,136,0.15); color: var(--accent); }
  .badge-err  { background: rgba(239,68,68,0.15); color: var(--err); }
  .badge-warn { background: rgba(245,158,11,0.15); color: var(--warn); }

  /* Log output */
  .log-box {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 16px;
    font-size: 12px;
    line-height: 1.7;
    white-space: pre-wrap;
    word-break: break-all;
    max-height: 300px;
    overflow-y: auto;
    margin: 16px 0;
    color: #94a3b8;
  }

  /* Webhook box */
  .webhook-box {
    background: rgba(0,255,136,0.05);
    border: 1px solid rgba(0,255,136,0.2);
    border-radius: 8px;
    padding: 20px;
    margin: 20px 0;
  }

  .webhook-url {
    font-size: 13px;
    color: var(--accent);
    word-break: break-all;
    margin: 8px 0 16px;
  }

  .secret-val {
    font-size: 13px;
    color: var(--warn);
    word-break: break-all;
    margin: 8px 0;
  }

  .instruction {
    counter-reset: inst;
    list-style: none;
    margin: 16px 0;
  }

  .instruction li {
    counter-increment: inst;
    padding: 8px 0 8px 36px;
    position: relative;
    border-bottom: 1px solid var(--border);
    color: #94a3b8;
    font-size: 13px;
    line-height: 1.6;
  }

  .instruction li:last-child { border-bottom: none; }

  .instruction li::before {
    content: counter(inst);
    position: absolute;
    left: 0;
    top: 8px;
    width: 22px;
    height: 22px;
    background: var(--accent2);
    color: #fff;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 700;
  }

  .instruction li b { color: var(--text); }

  .success-banner {
    background: rgba(0,255,136,0.08);
    border: 1px solid rgba(0,255,136,0.3);
    border-radius: 8px;
    padding: 24px;
    text-align: center;
    margin: 20px 0;
  }

  .success-banner .icon { font-size: 40px; margin-bottom: 12px; }
  .success-banner h3 { font-family: var(--head); color: var(--accent); margin-bottom: 8px; }
  .success-banner p { color: var(--muted); font-size: 12px; }

  .hint {
    color: var(--muted);
    font-size: 11px;
    margin-top: -10px;
    margin-bottom: 16px;
  }

  /* Cheatsheet */
  .cheat-tabs {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
    margin-top: 8px;
  }

  @media (max-width: 600px) {
    .cheat-tabs { grid-template-columns: 1fr; }
  }

  .cheat-section {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    overflow: hidden;
  }

  .cheat-title {
    background: rgba(124,58,237,0.15);
    color: #a78bfa;
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    padding: 8px 14px;
    border-bottom: 1px solid var(--border);
  }

  .cheat-row {
    display: flex;
    align-items: baseline;
    gap: 10px;
    padding: 7px 14px;
    border-bottom: 1px solid var(--border);
    transition: background 0.15s;
  }

  .cheat-row:last-child { border-bottom: none; }
  .cheat-row:hover { background: rgba(255,255,255,0.03); }

  .cheat-cmd {
    color: var(--accent);
    font-family: var(--mono);
    font-size: 11px;
    white-space: nowrap;
    cursor: pointer;
    flex-shrink: 0;
    transition: opacity 0.15s;
  }

  .cheat-cmd:hover { opacity: 0.7; }

  .cheat-desc {
    color: var(--muted);
    font-size: 11px;
    line-height: 1.4;
  }
</style>
</head>
<body>
<div class="wrap">

<header>
  <h1>⚡ Git Deploy Installer</h1>
  <p>Автодеплой с GitHub на хостинг через Webhook · v<?= INSTALLER_VERSION ?></p>
</header>

<!-- Steps nav -->
<div class="steps">
  <?php
  $steps = ['Окружение', 'Репозиторий', 'Webhook', 'Инструкция', 'Готово'];
  foreach ($steps as $i => $label):
    $n = $i + 1;
    $cls = $n == $step ? 'active' : ($n < $step ? 'done' : '');
  ?>
  <div class="step-item <?= $cls ?>">
    <span class="step-num"><?= $n < $step ? '✓' : $n ?></span>
    <?= $label ?>
  </div>
  <?php endforeach; ?>
</div>

<!-- STEP 1: Проверка окружения -->
<?php if ($step === 1): ?>
<div class="card">
  <h2><span class="num">1</span> Проверка окружения</h2>
  <p style="color:var(--muted);margin-bottom:20px;font-size:13px;">
    Проверим что на хостинге доступен shell_exec, git и права на запись.
  </p>

  <?php if ($action === 'check_env'): ?>
  <div class="checks">
    <?php foreach ($data as $key => $item): ?>
    <div class="check-row">
      <span class="check-key"><?= htmlspecialchars($key) ?></span>
      <span class="check-val"><?= htmlspecialchars($item['msg']) ?></span>
      <span class="badge badge-<?= $item['status'] ?>"><?= strtoupper($item['status']) ?></span>
    </div>
    <?php endforeach; ?>
  </div>

  <?php
  $has_error = array_filter($data, fn($i) => $i['status'] === 'error');
  if ($has_error): ?>
    <p style="color:var(--err);margin-top:16px;font-size:13px;">
      ❌ Есть критические ошибки. Деплой через webhook невозможен на этом хостинге.
    </p>
  <?php else: ?>
    <p style="color:var(--accent);margin-top:16px;font-size:13px;">
      ✓ Окружение готово. Переходим к настройке репозитория.
    </p>
    <br>
    <form method="post">
      <input type="hidden" name="action" value="next_step">
      <button class="btn" type="submit">Далее →</button>
    </form>
  <?php endif; ?>

  <?php else: ?>
  <form method="post">
    <input type="hidden" name="action" value="check_env">
    <button class="btn" type="submit">▶ Проверить окружение</button>
  </form>
  <?php endif; ?>
</div>
<?php endif; ?>

<!-- STEP 2: Настройка репозитория -->
<?php if ($step === 2): ?>
<div class="card">
  <h2><span class="num">2</span> Настройка репозитория</h2>

  <form method="post">
    <input type="hidden" name="action" value="check_repo">

    <label>URL репозитория (GitHub)</label>
    <input type="text" name="repo_url"
      value="<?= htmlspecialchars($_SESSION['repo_url'] ?? '') ?>"
      placeholder="https://github.com/user/repo.git">

    <label>Папка проекта на хостинге</label>
    <input type="text" name="project_dir"
      value="<?= htmlspecialchars($_SESSION['project_dir'] ?? __DIR__) ?>"
      placeholder="/home/s/user/site.ru/public_html">
    <p class="hint">Текущая папка: <?= __DIR__ ?></p>

    <label>Ветка</label>
    <input type="text" name="branch"
      value="<?= htmlspecialchars($_SESSION['branch'] ?? 'main') ?>"
      placeholder="main">

    <button class="btn" type="submit">▶ Проверить</button>
  </form>

  <?php if ($action === 'check_repo' && !empty($data)): ?>
  <div class="checks" style="margin-top:20px;">
    <?php foreach ($data as $key => $item): ?>
    <div class="check-row">
      <span class="check-key"><?= htmlspecialchars($key) ?></span>
      <span class="check-val"><?= htmlspecialchars($item['msg']) ?></span>
      <span class="badge badge-<?= $item['status'] ?>"><?= strtoupper($item['status']) ?></span>
    </div>
    <?php endforeach; ?>
  </div>

  <?php
  $has_git_error = isset($data['git_repo']) && $data['git_repo']['status'] === 'error';
  if ($has_git_error): ?>
    <p style="color:var(--warn);margin:16px 0;font-size:13px;">
      ⚠ Репозиторий не инициализирован. Инициализировать автоматически?
    </p>
    <form method="post">
      <input type="hidden" name="action" value="init_repo">
      <button class="btn" type="submit">⚡ Инициализировать репозиторий</button>
    </form>
  <?php endif; ?>
  <?php endif; ?>

  <?php if ($action === 'init_repo' && !empty($data)): ?>
  <div class="log-box"><?php
    foreach ($data as $item) {
        echo "$ " . htmlspecialchars($item['cmd']) . "\n";
        echo htmlspecialchars($item['out']) . "\n\n";
    }
  ?></div>
  <?php endif; ?>
</div>
<?php endif; ?>

<!-- STEP 3: Генерация webhook -->
<?php if ($step === 3): ?>
<div class="card">
  <h2><span class="num">3</span> Генерация Webhook</h2>

  <form method="post">
    <input type="hidden" name="action" value="generate_deploy">

    <label>Секретный ключ</label>
    <input type="text" name="secret"
      value="<?= htmlspecialchars($_SESSION['secret'] ?? '') ?>"
      placeholder="Оставь пустым — сгенерируется автоматически">
    <p class="hint">Используется для проверки подписи от GitHub</p>

    <button class="btn" type="submit">⚡ Создать deploy.php</button>
  </form>
</div>
<?php endif; ?>

<!-- STEP 4: Инструкция по настройке GitHub -->
<?php if ($step === 4): ?>
<div class="card">
  <h2><span class="num">4</span> Настройка Webhook на GitHub</h2>

  <div class="webhook-box">
    <label>Payload URL (вставить в GitHub):</label>
    <div class="webhook-url"><?= htmlspecialchars($_SESSION['webhook_url'] ?? '') ?></div>

    <label>Secret (вставить в GitHub):</label>
    <div class="secret-val"><?= htmlspecialchars($_SESSION['secret'] ?? '') ?></div>
  </div>

  <ol class="instruction">
    <li>Открой репозиторий на GitHub → <b>Settings → Webhooks → Add webhook</b></li>
    <li>В поле <b>Payload URL</b> вставь URL указанный выше</li>
    <li>В поле <b>Content type</b> выбери <b>application/json</b> (обязательно!)</li>
    <li>В поле <b>Secret</b> вставь секретный ключ указанный выше</li>
    <li>В разделе <b>Which events</b> выбери <b>Just the push event</b></li>
    <li>Нажми <b>Add webhook</b></li>
    <li>GitHub отправит тестовый ping — должна появиться зелёная галочка</li>
  </ol>

  <br>
  <form method="post">
    <input type="hidden" name="action" value="test_deploy">
    <button class="btn" type="submit">▶ Тест деплоя вручную</button>
  </form>
</div>
<?php endif; ?>

<!-- STEP 5: Готово -->
<?php if ($step === 5): ?>
<div class="card">
  <h2><span class="num">5</span> Готово</h2>

  <?php if (!empty($data)): ?>
  <div class="log-box"><?php
    echo "$ git fetch origin\n" . htmlspecialchars($data['fetch'] ?? '') . "\n\n";
    echo "$ git reset --hard origin/" . htmlspecialchars($_SESSION['branch'] ?? 'main') . "\n" . htmlspecialchars($data['reset'] ?? '');
  ?></div>
  <?php endif; ?>

  <div class="success-banner">
    <div class="icon">🚀</div>
    <h3>Автодеплой настроен!</h3>
    <p>Теперь каждый git push в ветку <b><?= htmlspecialchars($_SESSION['branch'] ?? 'main') ?></b> будет автоматически деплоиться на сервер</p>
  </div>

  <ol class="instruction">
    <li>Лог деплоев: <b><?= htmlspecialchars(dirname($_SERVER['REQUEST_URI'])) ?>/deploy.log</b></li>
    <li><b>Удали этот файл</b> (git-installer.php) с сервера — он больше не нужен</li>
    <li>Также удали <b>check.php</b> если создавал</li>
    <li>Файл <b>deploy.php</b> оставь — он принимает вебхуки</li>
  </ol>
</div>
<?php endif; ?>

<!-- Git Cheatsheet — всегда внизу -->
<div class="card" style="margin-top:40px;">
  <h2><span class="num" style="background:var(--accent2)">↓</span> Git — шпаргалка</h2>

  <?php
  $cheatsheet = [
    'Новый проект' => [
      ['git init',                                 'Инициализировать репо в текущей папке'],
      ['git add .',                                'Добавить все файлы в индекс'],
      ['git commit -m "Initial commit"',           'Первый коммит'],
      ['git branch -M main',                       'Переименовать ветку в main'],
      ['git remote add origin https://…/repo.git', 'Привязать удалённый репозиторий'],
      ['git push -u origin main',                  'Первый пуш + привязка ветки'],
    ],
    'Ежедневная работа' => [
      ['git status',               'Что изменилось'],
      ['git add .',                'Добавить все изменения'],
      ['git add путь/к/файлу',     'Добавить конкретный файл'],
      ['git commit -m "описание"', 'Зафиксировать изменения'],
      ['git push',                 'Отправить на GitHub'],
      ['git pull',                 'Получить обновления'],
    ],
    'Ветки' => [
      ['git branch',              'Список веток'],
      ['git checkout -b feature', 'Создать и переключиться на ветку'],
      ['git checkout main',       'Переключиться на main'],
      ['git merge feature',       'Слить ветку в текущую'],
      ['git branch -d feature',   'Удалить ветку'],
    ],
    'Remote & история' => [
      ['git remote -v',                      'Показать привязанные remote'],
      ['git remote set-url origin https://…','Изменить URL remote'],
      ['git log --oneline',                  'Краткий лог коммитов'],
      ['git diff',                           'Что изменилось (не добавлено)'],
      ['git reset --hard HEAD',              'Откатить все несохранённые изменения'],
      ['git reset --hard origin/main',       'Откатить до состояния на GitHub'],
    ],
  ];
  ?>

  <div class="cheat-tabs">
    <?php foreach ($cheatsheet as $section => $cmds): ?>
    <div class="cheat-section">
      <div class="cheat-title"><?= htmlspecialchars($section) ?></div>
      <?php foreach ($cmds as [$cmd, $desc]): ?>
      <div class="cheat-row">
        <code class="cheat-cmd"
          onclick="navigator.clipboard?.writeText('<?= htmlspecialchars($cmd, ENT_QUOTES) ?>');this.style.color='#fff';setTimeout(()=>this.style.color='',600)"
          title="Нажми чтобы скопировать"><?= htmlspecialchars($cmd) ?></code>
        <span class="cheat-desc"><?= htmlspecialchars($desc) ?></span>
      </div>
      <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
  </div>
</div>

</div>
</body>
</html>